version: '2'
services:
  detail_service:
     image: codeberserk/detailsservive:latest
     build:
           context: .
           dockerfile: Dockerfile
     container_name: Details_service
     volumes:
      - . :/var/lib/docker/volumes/
     command: java detailsService.jar
      