version: '2'
services:
  detail_service:
     image: codeberserk/detailsservive:latest
     build:
           context: .
           dockerfile: Dockerfile
     container_name: Details_service
     ports:
      - 8081:81
     volumes:
      - . :/var/lib/docker/volumes/va 
     command: java detailsService.jar
      